name: Create qa backwards merge
on:
  push:
    branches:
      - qa
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - name: Reset dev branch
        run: |
          git fetch origin qa:qa
          git reset --hard qa
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: qa
